name: translation_web_app
description: Translation application with speech recognition, translation and text-to-speech.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.13.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1

  # za backend?
  dio: ^5.5.0+1

  # voice input
  record: ^7.1.1

  # voice output
  audioplayers: ^6.5.0

  permission_handler: ^11.3.1

  path_provider: ^2.1.4

  uuid: ^4.4.2

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter